[package]
name = "pinset-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "pinset"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pinset-core = { path = "../pinset-core", features = ["dotnet-metadata", "flutter-metadata", "go-metadata", "installer", "java-metadata", "node-metadata", "npm-metadata", "project-discovery", "project-write", "python-metadata", "rust-metadata", "sources", "state-write"] }
serde.workspace = true
serde_json.workspace = true
terminal_size.workspace = true
toml.workspace = true
unicode-width.workspace = true

[dev-dependencies]
hex.workspace = true
sha2.workspace = true
tempfile.workspace = true
