[package]
name = "pinset-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false
build = "build.rs"
[[bin]]
name = "pinset"
path = "src/main.rs"
[dependencies]
pinset-core = { path = "../pinset-core" }
pinset-engine = { path = "../pinset-engine" }
clap.workspace = true
clap_complete = "4.5"
rpassword = "7.4.0"
serde_json.workspace = true
zeroize.workspace = true
[dev-dependencies]
tempfile.workspace = true
